isard-vdi/isard

CHANGELOG.md, dockers/app/supervisord.conf
=> This check before starting engine fixes some restart cases that may fail

CONTRIBUTING.md
This file is a guide on how to work with Git forks, Git Flow and GitHub
=> Created the CONTRIBUTING file

README.md
This fixes readme image that now will be in readthedocs from issue #26
=> Updated image link

README.md
Added the IsardVDI logo to the README. Also added the official Mastodon account
=> README branding

dockers/app-devel/Dockerfile, dockers/app-devel/requirements.pip3, dockers/app-devel/supervisord.conf, dockers/build-docker-images-devel.sh, dockers/devel-debug.yml, src/engine/config.py, src/engine/models/manager_hypervisors.py, src/engine/services/lib/qcow.py, src/engine/services/log.py, src/engine/services/threads/download_thread.py
=> download thread refactorized waiting other threads like disk operations

src/webapp/templates/pages/desktops_modals.html
I've changed the name shown in create template dropdown from Private to Template
=> Updated template name from Private to Template

src/webapp/templates/pages/about.html
=> Updated links

docker-compose.yml
This is needed for new extras folder and network sharing
=> updated volumes for compose v3.5

docker-compose.yml, dockers/remote-grafana/docker-compose.yml, dockers/remote-hyper/docker-compose.yml, extras/app-devel/devel-debug.yml, extras/grafana/docker-compose.yml, extras/grafana/remote-grafana.yml
Now it's more user-friendly. This is fixing #68
=> Changed docker restart policy to unless-stopped

src/webapp/lib/isardSocketio.py, src/webapp/static/admin/js/hypervisors_pools.js, src/webapp/templates/admin/pages/hypervisors_modals.html
Domain name in hypervisor pools can be edited in case it is not matching the one in the certificate file.
=> Domain can be updated

src/webapp/__init__.py, src/webapp/templates/admin/pages/domains_resources.html, src/webapp/views/AllowedsViews.py
This fixes some problems in resources views and alloweds.
=> Fixed resources page load and alloweds

src/engine/controllers/broom.py, src/engine/models/manager_hypervisors.py, src/engine/services/db/db.py, src/engine/services/db/domains.py, src/engine/services/lib/functions.py, src/engine/services/threads/download_thread.py, src/engine/services/threads/hyp_worker_thread.py, src/engine/services/threads/threads.py
Downloads bugs resolved. When engine start if some media or some domain status is Downloading. Kill curl, remove file and new status: DownloadFailed
=> fixing downloads bugs

extras/app-devel/devel-webapp.yml, src/webapp/lib/isardUpdates.py
Fixed a bug that didn't let register isard on updates if not registered during wizard
=> Fixed registering after install

src/webapp/admin/views/UpdatesViews.py, src/webapp/lib/isardUpdates.py, src/webapp/templates/admin/pages/updates.html
=> added reload button

extras/app-devel/devel-webapp.yml, src/engine/services/threads/grafana_thread.py
Missing conversion to int and also was not setting activation con config data.
=> Fixed grafana thread

src/webapp/config/populate.py
This will address part of #98 as it will force new install to use host-passthrough.
=> Force host-passthrough

src/engine/services/db/domains.py
bug fixed in the function that gets pools_hypervisors from a domain.
=> bug in get_pool_from_domain

src/webapp/wizard/WizardLib.py
this fixes a bug found when no registering available.
=> fixed bug when wizard was not registered

src/webapp/static/admin/js/media.js, src/webapp/static/js/media.js, src/webapp/templates/admin/pages/media.html, src/webapp/templates/admin/pages/media_modals.html, src/webapp/templates/pages/media_modals.html
We disabled win virtio checkbox as it seems it is no more needed for virtio installation in Windows. Plugging the default iso drivers you can get virtio drivers during install.
also fixed a minor bug while loading domains-media.
=> Disabled win virtio and fixed admin media

src/webapp/lib/admin_api.py, src/webapp/static/admin/js/domains.js, src/webapp/templates/admin/pages/domains_modals.html
Now the delete button will work as expected.
=> Bases and templates (with all hierarchy) can be deleted consistently

src/webapp/static/admin/js/domains.js, src/webapp/static/admin/js/users.js, src/webapp/static/js/viewer.js, src/webapp/templates/admin/pages/domains.html, src/webapp/templates/admin/pages/users_modals.html
disabled global actions as they are not needed in templates and bases.
=> Disabled desktop global actions in templates and bases

dockers/app/certs.sh
=> Fixed with netcat wait for ssh

src/webapp/lib/isardSocketio.py, src/webapp/static/admin/js/domains.js, src/webapp/static/admin/js/media.js, src/webapp/static/js/desktops.js, src/webapp/static/js/media.js, src/webapp/templates/pages/desktops_modals.html
Some minor bugfixes and also a major one that was blocking from creating templates at admin menu.
=> Fixed template creation from admin. Fixed deletion of medias.

src/engine/services/db/domains.py, src/webapp/admin/views/AdminViews.py, src/webapp/lib/admin_api.py, src/webapp/lib/api.py, src/webapp/lib/isardScheduler.py, src/webapp/lib/isardSocketio.py, src/webapp/static/admin/js/categories.js, src/webapp/static/admin/js/groups.js, src/webapp/static/admin/js/users.js, src/webapp/static/js/desktops.js, src/webapp/templates/admin/pages/config_modals.html, src/webapp/templates/admin/pages/users.html, src/webapp/templates/admin/pages/users_modals.html
This feature allows to have desktops with a timed use. From started time will have a limited configurable time to be used after which will be stopped or deleted.
CONFIGURATION:
1) Set new interval scheduler in config menu with the action "Check ephimeral domain status" and how often should be checked (i.e. 5 minutes). It will be the interval used to check for started domains with a timed use.
2) Add new category (groups not working yet) and now you'll find the option for Ephimeral desktops. Set the use time and the action to perform when time finishes.
3) Add users to this category. New desktops created by this users will have limited use to the time set in their category. An accurate remaining time will be shown in desktop description after it is started.
=> Timed desktops

src/webapp/auth/authentication.py, src/webapp/lib/admin_api.py, src/webapp/lib/api.py, src/webapp/lib/isardScheduler.py, src/webapp/static/admin/js/categories.js, src/webapp/static/admin/js/groups.js, src/webapp/static/js/desktops.js, src/webapp/templates/admin/pages/users_modals.html, src/webapp/views/LoginViews.py
This adds the option to add predefined desktops to user at login time if he hasn't got it.
It should be configured at categories or groups creation time.
This is progress in #124
=> Auto user desktops

src/webapp/lib/isardViewer.py
This is a bug when using NAT to access remotely to isard.
=> Fixed remote nat port as string0

src/webapp/lib/admin_api.py
This will add the predefined desktops when creating users in bulk.
=> Add bulk users option to auto create desktops

src/webapp/lib/isardViewer.py
The port was not converted to string.
=> Fixed port for natted vnc web browser

src/webapp/admin/views/AdminHypersViews.py, src/webapp/admin/views/AdminViews.py, src/webapp/admin/views/UpdatesViews.py, src/webapp/admin/views/decorators.py, src/webapp/lib/admin_api.py, src/webapp/views/LoginViews.py, src/webapp/views/decorators.py
This fixes a critical bug when an administrator updated a user password as it updated all the users to that password. It missed the user id.
The other fix added is about redirects and ports. Some pages where not redirecting to the natted port if you accessed your IsardVDI interface with default 443 https port.
=> Fix admin user pwd update and redirects

CHANGELOG.md, src/webapp/admin/views/AdminHypersViews.py, src/webapp/admin/views/AdminViews.py, src/webapp/admin/views/UpdatesViews.py, src/webapp/admin/views/decorators.py, src/webapp/lib/admin_api.py, src/webapp/views/LoginViews.py, src/webapp/views/decorators.py
This minor release is needed as we found two critical bugs.
1) resetting user passwords in admin pannel did a bulk update of all users passwords.
2) port access on other than 443 through https did not redirect correctly.
=> Release 1.1.1

dockers/app/certs.sh
This bug was preventing the server to connect to the hypervisor through
SSH
=> Fix Hypervisor SSH bug

extras/app-devel/devel-debug.yml, src/engine/models/domain_xml.py, src/engine/services/db/db.py, src/webapp/config/populate.py, src/webapp/config/upgrade.py
rewrite XML when start domain, changing compression and other spice properties in entry default in graphics table.
=> rewrite video copmresion

docker-compose.yml
Like the instructions of webpage https://isardvdi.com
=> Allow the use of docker-compose.yml with an empty TAG variable

src/webapp/templates/admin/pages/users_detail.html
=> Hide delete user button because doesn't work

src/webapp/templates/pages/user_profile.html
=> Remove last access from user profile page

engine/engine/engine/models/domain_xml.py, webapp/webapp/webapp/lib/isardSocketio.py, webapp/webapp/webapp/static/js/snippets/domain_hardware.js, webapp/webapp/webapp/templates/snippets/domain_hardware_edit.html
This allows multiple network interface selection
=> Allows multiple network interface selection

docker/hypervisor/run.sh
Manage vms through libvirt worked but there were permissions problems when trying to manage with virsh utils.
=> fixed permissions for qemu default user

webapp/webapp/webapp/auth/authentication.py, webapp/webapp/webapp/config/ldapauth.py, webapp/webapp/webapp/templates/admin/pages/config.html
This fixes users and categories for ldap auth
=> ldap fixes for this version

webapp/webapp/webapp/static/admin/js/users.js, webapp/webapp/webapp/templates/admin/pages/users_modals.html
=> Fix "password do not match" with unique HTML ids

webapp/webapp/webapp/static/js/desktops.js, webapp/webapp/webapp/templates/pages/desktops_modals.html
Fixes the validation itself and the error messages that are shown with the default template name.
Please see also the commits comments.
Closes #143
=> Fix webapp template name validation

webapp/webapp/webapp/lib/admin_api.py, webapp/webapp/webapp/lib/isardSocketio.py, webapp/webapp/webapp/static/admin/js/users.js
It will fix exception when csv line ends with return carriage \r
=> Fixed return carriage strip on uploaded csv

docker/hypervisor/vlans-db.py
=> replaced envvar for db from hypervisor

docker/hypervisor/vlans-db.py, docker/hypervisor/vlans-discover.sh
Fixed bug that overwrites existing vlans.
=> Avoid updating existing vlans in db

webapp/webapp/webapp/static/js/desktops.js
=> Fix desktop delete button enabled when runs

docker/hypervisor/vlans-db.py
This fixes incorrect bridge mapping when using vlans
=> fixed bridge mapping

webapp/webapp/webapp/static/admin/js/domains_resources.js, webapp/webapp/webapp/templates/admin/pages/domains_resources_modals.html
Removed net field from web interface as now it has no function (before it was used to auto-map networks to domains based on clients ip address)
=> removed net from web ui

docker/video/docker-entrypoint.sh, docker/video/haproxy.conf, isardvdi.cfg.example
Added dynamic dns resolver to haproxy and fixed explanation for video proxy certificates when using standalone hypervisor
=> Standalone hypervisor

engine/engine/initdb/populate.py, webapp/webapp/share_all.py, webapp/webapp/webapp/auth/authentication.py, webapp/webapp/webapp/lib/load_config.py, webapp/webapp/webapp/views/DesktopViews.py
Added a shares between categories script with related code in app
=> Added a shares between categories script with related code in app

webapp/webapp/webapp/lib/load_config.py
Fixed bug when shares not present in config (old develop versions)
=> Fixed bug when shares are not present in config

docker/hypervisor/networks/default.xml
This increases possible guests to 1000 instead of 252 per hypervisor.
=> New dhcp range with 1000 possible hosts

engine/engine/initdb/populate.py, webapp/webapp/webapp/templates/admin/pages/domains_resources_modals.html
It showed Kbps instead of KBytes/s
=> Fixed units in net QoS modal

api/src/api/libv2/quotas.py, api/src/api/libv2/webapp_quotas.py, webapp/webapp/webapp/lib/quotas.py
Fixed bug in mem percentage that failed to limit by memory
=> Fixed bug in mem percentage that failed to limit by memory

webapp/webapp/webapp/lib/api.py
Fix messages like "Medi deleting success" by "Media deleting success".
=> Fix "Medi" messages of webapp

frontend/yarn.lock
https://github.com/isard-vdi/isard/network/alert/frontend/yarn.lock/node-forge/open
=> Upgrade node-forge of frontend

webapp/webapp/webapp/templates/admin/pages/users_detail.html
=> Fix the view of quota and limits of user details

backend/isard/user.go
Without these changes backend is wiping the name and email of local users.
=> Fix user update by backend

webapp/webapp/webapp/static/js/snippets/quota.js
User details limits form does nothing, so if it is locked doesn't confuse users.
=> Fix user details limits form, locking it

webapp/webapp/webapp/lib/isardSocketio.py, webapp/webapp/webapp/static/admin/js/domains.js
=> Fix media editing on admin menu desktops of webapp

webapp/webapp/webapp/static/admin/js/domains.js
=> Fix webapp showing media in desktops of admin menu

build.sh
This is needed when we want and standalone video (video+squid+websockify) in infrastructure deployments.
=> video-standalone for infrastructure

.gitignore, build.sh
=> docker-compose no-stats flavor

sysadm/debian_firewall.sh, sysadm/debian_firewall_hyp.sh
=> Fixed bug in iptables 1.8

api/src/api/libv2/isardViewer.py, api/src/api_client_test.py, docker/static/noVNC/index.html, webapp/webapp/webapp/lib/isardViewer.py
This will show desktop name in HTML5 top status bar, at least in admin webapp.
We should check if any change is needed to have the vmName parameter in the cookie at frontend.
=> Added vmName parameter on html5 viewer to show on top bar

webapp/webapp/webapp/lib/isardSocketio.py, webapp/webapp/webapp/static/admin/js/domains.js, webapp/webapp/webapp/static/js/desktops.js
In admin the updating of desktops failed due to a bug in creating dict.
=> Fixed bug that did not allow domains edit

docker/hypervisor/Dockerfile, docker/hypervisor/qemu-kvm
this forces spice audio even if vnc is activated in domain.
=> working audio

docker/hypervisor/run.sh
Solves problem with left files in /run
=> Fixes bug when restarting hypervisor

docker/hypervisor/networks/shared.xml
Fixed range with shared network that was out of network definition in shared
=> fixed shared range

CHANGELOG.md
=> Fix hypervisor spice certs owner when upgrading

webapp/webapp/webapp/static/js/desktops.js, webapp/webapp/webapp/templates/admin/pages/domains.html, webapp/webapp/webapp/templates/pages/desktops_modals.html
This will bring a bigger and more cleaner add desktop modal
=> Bigger add desktop modal and new cleaner selected styles

engine/engine/initdb/populate.py, engine/engine/initdb/upgrade.py, webapp/webapp/webapp/lib/isardUpdates.py
This will use https with the new repository for updates.
=> Will allow updates through new repository and https

webapp/webapp/webapp/templates/pages/desktops.html
Updated viewer info in desktops page.
=> updated viewer info

docker/portal/Dockerfile
Fixes changes in Dockerfile docker-entrypoint.sh file that didn't handle well our Dockerfile from that one.
https://github.com/docker-library/haproxy/commit/82ff028a25c55c36e8c39b16390e4e04efa2bc4a
=> fixed bug in new haproxy dockerfile

webapp/webapp/webapp/views/AllowedsViews.py, webapp/webapp/webapp/views/decorators.py
This change fixes a bug that did not allow to populate allowed rights on templates when manager.
=> Fixed bug that did not allow manager to access template allows

webapp/webapp/webapp/lib/api.py
The desktops were created to all the selection if left empty (apply to all) when used by managers instead of filtering per category.
=> Fixed bug with perms when creating desktops in bulk

docker/video/Dockerfile
=> New haproxy container fixes docker-entrypoint at new place
