src/engine/services/lib/download.py
src/engine/services/lib/qcow.py
src/webapp/lib/isardSocketio.py

When creating a template df command is launched to know free space. This command had two lines of output if the device of the mount point is too large.
When adding media like an iso from web server, if the URL failed these media disappear from the list.
Redirect testing URL is activated

bugs creating template and download media

---

src/webapp/templates/pages/desktops_modals.html

Fixed minimal length of 4 characters for new templates. Fixes #86

Fixed minimum template name length

---

dockers/app/certs.sh
extras/app-devel/devel-infrastructure.yml
extras/remote-hyper/README.md
extras/remote-hyper/docker-compose.yml
extras/remote-hyper/infrastructure-isard.yml
src/engine/models/hyp.py

Fixed bugs in infrastructure (when you have remote hypers with ports different than 22):
- Now isard-app container will keep remote hyper keys between docker restarts
- Fixed bug in engine that forbid the use of ports different than 22 to connect to hypervisors.
- Added infrastructure-isard.yml to remote-hyper extras to bring up IsardVDI without the need to bring up isard-hypervisor.

Fixed remote-hyper and port

---

webapp/docker/Dockerfile

% docker-compose build isard-webapp
Building isard-webapp
Step 1/14 : FROM alpine:3.11.3 as production
---> e7d92cdc71fe
Step 2/14 : MAINTAINER isard <info@isard.com>
---> Using cache
---> 11d6d22f6bc9
Step 3/14 : RUN apk add --no-cache     yarn     py3-paramiko==2.7.1-r0     py3-lxml==4.4.2-r0     py3-openssl==19.1.0-r0     py3-bcrypt==3.1.7-r2     py3-gevent==1.4.0-r2     py3-flask==1.0.4-r0     py3-netaddr==0.7.19-r4     py3-requests==2.22.0-r0         py3-pyldap==3.2.0-r1     curl==7.67.0-r0     openssh-client==8.1_p1-r0     sshpass==1.06-r0     supervisor==4.1.0-r0
---> Running in c70e902bc722
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints: …

Update curl of isard-webapp

---

docker/hypervisor/Dockerfile
docker/hypervisor/vlans-add.sh
docker/hypervisor/vlans-db.py
docker/hypervisor/vlans-discover.sh

It updates from hypervisor the database with the found vlans. In infrastructure installation (multiple hypervisors) the same vlans should be in all the hypervisors.

Updates database with found vlans

---

docker/hypervisor/Dockerfile

isard-hypervisor    | auto-generate-certs.sh: line 15: openssl: not found

Add missing openssl to isard-hypervisor

---

docker/hypervisor/Dockerfile

Reverts isard-vdi/isard#233 as this is not working. Needs testing.

Revert "Add missing openssl to isard-hypervisor"

---

ymls/devel/isard-db.yml.devel
ymls/isard-db.yml

This is now required for remote hypervisors to update isard-db. Firewall must be correctly set to avoid security issues.

Open port, filter with firewall

---

webapp/webapp/webapp/lib/isardSocketio.py

"Create desktop" button of "Create desktop from media" form of admin menu media doesn't work.
```
Traceback (most recent call last):
File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
File "/usr/lib/python3.8/site-packages/socketio/server.py", line 636, in _handle_event_internal
r = server._trigger_event(data[0], namespace, sid, *data[1:])
File "/usr/lib/python3.8/site-packages/socketio/server.py", line 665, in _trigger_event
return self.handlers[namespace][event](*args)
File "/usr/lib/python3.8/site-packages/flask_socketio/__init__.py", line 223, in _handler
return self._handle_event(handler, message, namespace, sid,
File "/usr/lib/python3.8/site-packages/flask_socketio/__init__.py", line 591, in _handle_event
ret = handler(*args)
File …
```

Fix desktop creation from admin menu media of webapp

---

webapp/webapp/webapp/static/admin/js/domains.js

Fix the 500 Internal Server Error with "Wrong parameters." when deleting
a desktop from admin menu.

Fix delete desktop from admin menu of webapp

---

engine/engine/engine/services/lib/qcow.py

```
2020/10/21 16:08:56 842 - ERROR - disk_op_isard-hypervisor: Traceback: Traceback (most recent call last):
File "/isard/engine/services/threads/disk_operations_thread.py", line 57, in disk_operations_thread
launch_action_create_template_disk(action,
File "/isard/engine/services/threads/threads.py", line 249, in launch_action_create_template_disk
error, backing_chain_domain, backing_chain_template = verify_output_cmds3(cmds_done, path_domain_disk,
File "/isard/engine/services/lib/qcow.py", line 344, in verify_output_cmds3
return error, backing_chain_domain, backing_chain_template
UnboundLocalError: local variable 'backing_chain_domain' referenced before assignment
```

Fix backing_chain_domain and backing_chain_template referenced before assignment

---

docker-compose.yml
docker-compose.yml.example
docker/hypervisor/Dockerfile
docker/hypervisor/run.sh
ymls/isard-hypervisor-vlans.yml
ymls/isard-hypervisor.yml

Fixes:
```
2020/10/24 22:32:47 841 - ERROR - try_isard-hypervisor: fail_connected_reason: ssh authentication fail when connect: Host key for server 'isard-hypervisor' does not match: got 'AAAAC3NzaC1lZDI1NTE5AAAAIHcSuxaEYXnbxMcKXi4qhDjJKr2OupGeMjdOUx58j5GH', expected 'AAAAC3NzaC1lZDI1NTE5AAAAIFY4pytnGBev53Q2fwdlrRYgR45whpCjzl5rndV7qRVQ'
```
To preserve SSHd keys used before this commit, you could run the following commands while old hypervisor container is running:
```
mkdir -p /opt/isard/hypervisor
docker cp isard-hypervisor:/etc/ssh /opt/isard/hypervisor/sshd_keys
rm /opt/isard/hypervisor/sshd_keys/moduli /opt/isard/hypervisor/sshd_keys/ssh_config /opt/isard/hypervisor/sshd_keys/sshd_config
```
See also the following comment to see instructions used to move keys from old container to …

Preserve hypervisor SSHd keys

---

webapp/webapp/webapp/static/admin/js/users.js

Reproduce reloading the page of users and editing one. Correct fields are marked as wrong.
This change run validator after refill the form.

Fix user edit form invalid warnings

---

engine/engine/engine/models/pool_hypervisors.py
engine/engine/engine/services/balancers/balancer_interface.py
engine/engine/engine/services/balancers/central_manager.py
engine/engine/engine/services/balancers/round_robin.py

```
2020-10-21 09:46:41,958 - downloads - INFO - download_changes - waiting an hypervisor online to launch downloading actions
Exception in thread download_changes:
Traceback (most recent call last):
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/isard/engine/services/threads/download_thread.py", line 459, in run
next_hyp = self.manager.pools[pool_id].get_next()
File "/isard/engine/models/pool_hypervisors.py", line 83, in get_next
return self.balancer.get_next(*args)
TypeError: get_next() takes 2 positional arguments but 4 were given
```
Related to #279

Fix BalancerInterface.get_next() parameters

---

build.sh
ymls/isard-hypervisor-standalone.yml

When using a dedicated video proxy the remote hypervisors should be run without the video proxies and should also open ports 5900-6899 for video requests coming from the video proxy host. 
Of cours this ports should be opened ONLY from the video proxy host.

added novideo hypervisor

---

api/src/api/libv2/api_desktops_nonpersistent.py

Desktop edit form limits the length name of desktops to 40 characters but name cannot be edited. The form becomes unusable if desktop have a longer name. This change fixes it limiting the name length of created non-persistent desktops.

Fix api by limiting the name length of non-persistent desktops

---

docker/hypervisor/run.sh

Just added an sleep between virtlogd and libvirtd that avoids race condition between them that fails to start hypervisor.

relaxed time between virtlogd and libvirt that avoids race bug sometimes

---

docker/portal/haproxy.conf

This new config solves the spice delay and usb passthrough problems we were having.

fixes for tcp mode to reduce spice delay and usb passthrough

---

api/src/api/libv2/webapp_quotas.py
docker-compose-parts/engine.devel.yml
engine/engine/engine/controllers/ui_actions.py
engine/engine/engine/services/db/domains.py
engine/engine/engine/services/evaluators/ux_eval.py
webapp/webapp/webapp/lib/admin_api.py
webapp/webapp/webapp/lib/api.py
webapp/webapp/webapp/lib/isardSocketio.py
webapp/webapp/webapp/lib/quotas.py
webapp/webapp/webapp/static/admin/js/domains.js
webapp/webapp/webapp/static/js/desktops.js
webapp/webapp/webapp/static/js/snippets/domain_hardware.js
webapp/webapp/webapp/static/js/snippets/domain_hotplugged.js
webapp/webapp/webapp/templates/admin/pages/domains_modals.html
webapp/webapp/webapp/templates/admin/pages/templates_detail.html
webapp/webapp/webapp/templates/pages/desktops_detail.html

This will let managers and administrator roles to force an hypervisor for a desktop or template. This is useful right now when you want to use shared network between hosts and you don't want to mess with infrastructure configurations: just force those desktops or the template from where are derived to an hypervisor.
The derived desktops will inherit the forced_domain defined in parent template at creation time.
The templates created from a desktop with forced_hyp will not inherit that parameter. It can be set in the newly created template if needed for next derived desktops.

Force hypervisor

---

docker/hypervisor/networks/shared.xml

Without this change we are leaving 799 hosts outside DHCP range and only 222 host for the DHCP range.
With this change we are leaving 32 hosts outside DHCP range and 990 hosts for
the DHCP range.
See also: https://github.com/isard-vdi/isard/pull/350#pullrequestreview-555299684

Fix hypervisor shared network dhcp range

---

webapp/webapp/webapp/admin/views/AdminViews.py
webapp/webapp/webapp/static/admin/js/config.js

It didn't populate correctly tables where description was missing. Also fixed bug when selecting none ('Choose...')

fixed bug when restoring tables from backup

---

docker/portal/haproxy.conf

The db access withouth trailing slash was not working, even with trailing slash. This allows access without trailing slash (/debug/db)

fixed db path

---

docker/hypervisor/run.sh

This is a minor change that will avoid hypervisor to fail if it was restarted while still with domains running.

Fixes hyper restart with domains and networks running

---

docker/hypervisor/run.sh
webapp/webapp/share_none.py
webapp/webapp/webapp/lib/admin_api.py
webapp/webapp/webapp/lib/api.py
webapp/webapp/webapp/lib/isardSocketio.py
webapp/webapp/webapp/static/admin/js/domains.js
webapp/webapp/webapp/static/js/media.js
webapp/webapp/webapp/static/js/snippets/alloweds.js
webapp/webapp/webapp/templates/snippets/alloweds_add.html
webapp/webapp/webapp/views/DesktopViews.py

This fix will allow to keep the default 'non-shared' templates between categories while still allowing categories to get templates shared by the admin.
Also disabled the roles and categories fields in alloweds sharing for non admins. The idea behind is that non admins can organize their users by using the groups and using them to share templates within their category.
If an admin wants to share a template from a category to another category then he has to create a desktop from that template, convert it to template and share it as he wants.

fixed alloweds

---

.gitlab-ci.yml

```
$ wget https://isardvdi.com/docker-compose.yml
$ docker-compose -v
docker-compose version 1.25.0, build unknown
$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.isard-engine.depends_on contains an invalid type, it should be an array
```

Fix docker-compose depends_on contains an invalid type issue
